[build]
  base    = ""
  publish = "/build"
  command = "npm run build"

[context.master]
  command = "echo $ACCESS_TOKEN; npm run build;"
[context.master.environment]
  ACCESS_TOKEN = "I'M IN PRODUCTION"

[context.staging]
  command = "echo $ACCESS_TOKEN; npm run build;"
[context.staging.environment]
  ACCESS_TOKEN = "I'M THE STAGING BRANCH"

[context.deploy-preview.environment]
  command = "echo $ACCESS_TOKEN; npm run build;"
  ACCESS_TOKEN = "I'M A PULL REQUEST TO MASTER"

[context.branch-deploy]
  command = "echo $ACCESS_TOKEN; npm run build;"
[context.branch-deploy.environment]
  ACCESS_TOKEN = "I'M A BRANCH BUILD TRIGGERED BY A DEPLOY HOOK"